### ISSUE TITLE
subdocapi-draft

### ISSUE THREAD

**Issue by ToddGreenstein** [couchbaselabs/sdk-rfcs#12]
Answers to Outstanding Questions:
**Array method naming: append and prepend vs `extend?**
Append and Prepend is my preference
**Array prefix: arrayXXXX?**
Arrayinsert/arrayprepend is fine
**How should multi mutation errors be reported?**
Report Multiple Errors with as much information as possible
**For languages supporting overloads, should one simply overload get(), upsert(), etc.**
No overloading these base methods is my preference

**Comment by ingenthr** [comment]
@mnunberg can you see that these are handled in the current draft?

**Comment by mnunberg** [comment]
It seems consensus is in favor of various pushXXX methods for array naming.
Array prefix is no longer needed except in case of Insert (vs ArrayInsert)
MultiMutation errors are reported at the top-level with an indicator pointing to sub-errors
No overloads.

I think we can close all of these.
