### ISSUE TITLE
subdoc: push_front/push_back => push_first/push_last

### ISSUE THREAD

**Issue by mnunberg** [couchbaselabs/sdk-rfcs#28]
The former names C++ functions, and it's not immediately clear what the "front" and "back" actually mean (I'll tell you that these were confusing to me when I was first learning C++).

I believe first/last more intuitively reflects the location of where the items are added to. We can even do 'push_left' and 'push_right'...

**Comment by mnunberg** [comment]
Upon further consideration, we might use:

* push_at
* push_right
* push_left

**Comment by brett19** [comment]
I really like `push_at`, but the `push_left` and `push_right` are a bit icky.

**Comment by simonbasle** [comment]
@brett19 @mnunberg wasn't there a vote for that naming? what was the result? can we commit to anything?

**Comment by brett19** [comment]
ArrayAppend, ArrayPrepend were the winners, with PushFront, PushBack having similar support but falling in second.

**Comment by mnunberg** [comment]
So:

array_append
array_prepend
array_insert
array_addunique

Good?

**Comment by simonbasle** [comment]
Sounds good to me!

**Comment by jeffrymorris** [comment]
+1
