### ISSUE TITLE
0013_Define Error Code Brackets

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/sdk-rfcs#32]
Objective here is to be able to have error codes in advance of new features being added.  For instance, 0xb0 through 0xdf are retryable while 0xa0 through 0xaf indicate permanent failure.

This will improve situations like the possible scenarios behind MB-13156

**Comment by ingenthr** [comment]
Draft posted. https://docs.google.com/document/d/1LO2D-bGXXSHM1QXLQjjcIKaXt2IKovQFzhdJh-XVtuo/edit#

**Comment by ingenthr** [comment]
@mnunberg 's draft that supersedes the one identified above is posted: https://docs.google.com/document/d/12VpZPhWYHf69QtGKKTLlZG6j9sc3K9D1bMcbnM1F5Uk/edit#

**Comment by mnunberg** [comment]
Closing this issue - we're working on an RFC already!
