### ISSUE TITLE
[gardening] Move Cluster Level Auth RFC to markdown AND into accepted

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/sdk-rfcs#61]
https://docs.google.com/document/d/1CD5OL1ez7euCiLJT91zdWY9R4tW_bkGZ0wsFk1UDtyY/edit#heading=h.7u2v4nrmd4qr

is accepted and needs to be moved over

**Comment by avsej** [comment]
Fixed by cafce5ae5a2ce560f0b4b66fd03714f21c21eb6d
