### ISSUE TITLE
Field-Level Encryption

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/sdk-rfcs#69]

**Comment by daschl** [comment]
Don pointed me to this: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine

**Comment by jeffrymorris** [comment]
Thanks @daschl

**Comment by daschl** [comment]
Assigned RFC ID 32

**Comment by dnault** [comment]
@jeffrymorris Ready to close this?
