### ISSUE TITLE
Field Level Encryption - Some thoughts

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/sdk-rfcs#86]
1. In addition to making the Key Store abstract, making the encryption/decryption system abstract should have value as well.  For example, a .NET system could use the DataProtection APIs (https://github.com/aspnet/DataProtection) to perform the actual encryption/decryption. Of course, this particular example would limit cross-SDK compatibility, so I wouldn't recommend it for the default, but the extensibility could have value.

2. For the key store, it should have some mechanism for handling key rotation.  Rotating keys regularly is a key component of many security regulations, such as PCI.

**Comment by jeffrymorris** [comment]
Thanks for the feedback @brantburnett

**Comment by jeffrymorris** [comment]
@brantburnett -

1- The encryption/decryption system is based off the ICryptoProvider interface which can be implemented as any FIPS-140-2 compliant algorithm. 

2 - Key rotation was discussed but pushed out to a future version, mostly to lower the scope of the initial implementation and to buy time to assess customer needs/requirements for key rotation.

**Comment by dnault** [comment]
Hi @brantburnett , sorry for resurrecting this old issue. If you're still interested, what would you like to see in a key rotation solution?

**Comment by brantburnett** [comment]
@dnault honestly, I'm not a 100% sure, other than I know it's something we'd need. Our primary use for encryption is PCI or GDPR compliance, and key rotation is a part of those standards. I think every 3 months?

I guess the key would be that the field-level encryption data stores some kind of key identifier. That way when decrypting the system would know which key to use to decrypt.

A secondary feature would be some system to gradually go through data encrypted with old keys and decrypt then re-encrypt using newer keys. But to me, that feature is a bit less important, as it can be bolted on at a later time. Adding key identifiers up-front to the design would be more important, as adding them later and maintaining compatibility would be difficult.

**Comment by dnault** [comment]
Hi @brantburnett,

Just a quick note to say we've incorporated this feedback into the design of Field-Level Encryption for SDK 3 (RFC 64):

* Custom `Encrypter`s and `Decrypter`s can be registered with the `CryptoManager`.

* The new `Keyring` abstraction makes it possible for developers to implement key rotation.
 
The secondary feature of re-encrypting old fields remains out-of-scope, but the new FLE API makes this easier for developers to do on their own. Specifically, the developer no longer needs to specify the key when decrypting (the FLE framework now automatically uses the same key that was used to encrypt the field).

Thanks,
David
